h_ch: [16, False]
ver_ch: [16, True]
vol_ch: [16, True]
split: [True, 0.1] # [percentage, value]
batch_size: 8
in_channels: 1
out_channels: 13
hidden_dim: 8
n_heads: 8
n_classes: 13
positional_dim: 128
mv_in_channels: 48
blocks: 1
dropout_gatr: 0.4
dropout_final: 0.2
lr: 0.001
max_epochs: 2
patience: 20
window_size: 16
